### ISSUE TITLE
Koodikatselmointi | Project review

### ISSUE THREAD

**Issue by yusifsalam** [Raincoon/OddRealmBotany#1]
## The setup
Repository was cloned 1.10.2019 at 12:40 EEST, Heroku app was tested 13:40-14:50 EEST. 

What I did:

1. open heroku app and sign up with a new user
2. create three plants
3. create three tags
4. edit plant name and mature time
5. add tags to plants
6. remove plant
7. log out and create new user, repeat steps 2 and 3. 
8. log out and log in with test account, repeat steps 2 and 3. 
9. review code

## General impressions
The functionality that I tested seemed to work well and I did not encounter any errors. I was able to add plants and tags, as well as remove and edit plants, just as promised in the feature list of the documentation. I tried to click the sign up button with blank input fields, and the app correctly informed me of that, same thing with creating new plants and tags. I also tried to input a string as mature time when creating a new plant, which was also rejected by the validator. Creating a duplicate user was unsuccessful as well, as I was instructed to pick a different username. 

Database structure (presented in the class diagram) seems to support the planned features of the application well. Primary and foreign keys are not marked in the class diagram but they are both self-evident. Plant mature time is chosen to be an integer, which in my opinion should be float. Otherwise, database design is fine for the job. 

Bootstrap is used for the styling of the application, which is a fine choice given the course setting. However, submit buttons are standard HTML ones, which adds styling inconsistency. The text in the top panel can be difficult to read, as the font color is similar to the color of the panel. The placement and sizing of plant action buttons could also be improved, as in the current version there is no clear separation which button belongs to which plant. The main content is not centered on the page nor does it have left/right margins, which is not ideal on widescreen monitors. Overall, the UI and UX is functional but could be improved with a few minor changes. 

## Code quality
Code is of good quality and is easy to read and understand. Variable and class names are descriptive, and same is true for function names. The addition of comments also makes the code easier to follow. SQL injection is prevented with the use of SQLAlchemy params, very good. Database schema also matches that presented in the class diagram of documentation. 

There are some inconsistencies with the code styling, namely both single and double quotes are used interchangeably. PEP-8 standard isn't fully fulfilled but I don't believe that's an issue in this case. The base model class could probably be renamed to something more descriptive, as class name _"Id"_ is rather confusing. Other than that, I don't have any issues with code quality. 

## Issues encountered
There were some interesting moments:

- when signing up, I managed to create a user whose username and password were 1 character long and a user with unreasonably long username and password. There should probably be a minimum and maximum lengths for both of those fields.
- I was able to create duplicate tags. Validation should probably ensure tags are unique.
- I was able to create plants with identical names. Validation should probably ensure plant names are unique, as well as have minimum length for plant name. 
- when I tried to input a string into mature time of a plant, the error that I got did not indicate that the mature time should be an integer and instead informed that the mature time is a required field. 
- plant count displays wrong value. Instead of showing the count for a user, the entire database plant count is shown. The SQL statement inside _count_plants_from_user_ seems to be the cause of the issue. 

Overall, the project seems to have progressed fine and is in line with the expectations at this stage of the course, good job :)

**Comment by RainSalamander** [comment]
Kiitos palautteesta!  
Very useful comments, thank you!
