### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by simunni** [Raincoon/OddRealmBotany#2]
### Sovelluksen toiminta
Testattu paikallisesti ja herokussa 15.10.2019 klo 18.00.
Molemmat vaikuttavat toimivan täsmälleen samalla tavalla.

Sovellus näyttäisi toimivan pääsääntöisesti käyttötapausten mukaisesti.
Puuttuvia toiminnallisuuksia vaikuttaisi olevan järjestyksen muuttaminen sekä salasanan vaihtaminen.

Ilman koodia katsomatta ohjelmassa näyttäisi olevan validoinnin kanssa logiikka virhe, sillä kasvuajan ollessa 0 saadaan virhe "Mature Time: A number input between 0 and 120 is required". Muuten näyttäisi toimivan oiken mallikkaasti sovellus.

### Koodi
Koodi on selkeää sekä metodit että muututjat on nimetty johdonmukaisesti. Koodista löytyy myös kommentointia jäsennellysti. Tämä ei ole välttämätöntä, kunhan muuttujat on nimetty asiayhteyden mukaisesti, jolloin koodi itsessään kertoo kontekstin riittävällä tarkkuudella, mutta tämä on yleinen makuasia.

Laajempaa yhteenveto kyselyä, jossa tauluja yhdisteltäisiin, en löytänyt.

### Ulkoasu
Ulkoasu on ihan mielyttävä yksinkertainen. Sisältö esitellään hyvin taulukossa, josta pääsee muokkaamaan jokaisen tietoja.

### Dokumentaatio
Tietokantakaavio on oikein tehty. Userstorysta kannattaa karsia toteuttamatta jääneet toiminnallisuudet ennen viimeistä palautusta.

Tietokannan create lausekkeet sisältävän tiedoston voisi nimetä .sql päätteiseksi.
Lisäksi ohjelmalle kannattaa lisätä asennnusohjeet dokumentaatioon.

Kokonaisuudessaan näyttäisi toimivan ihan hyvin sovellus päätoiminnallisuuksiltaan. Pidin työn yksinkertaisuudesta, joka auttaa pitämään koodinkin siistinä.

**Comment by RainSalamander** [comment]
Kiitos kommenteista! Hyvä kun mainitsit tuon logiikkavirheen, en olisi muistanut itse tuota tarkistaa puuttuvia ominaisuuksia lisäillessä ennen loppupalautusta :D
